### ISSUE TITLE
Support Groups

### ISSUE THREAD

**Issue by Naatan** [cunla/ghactions-toolbar#26]
**Is your feature request related to a problem? Please describe.**
Output of certain actions can be verbose, to address this github actions allows you to define groups which are collapsed by default and can be expanded by the user.

**Describe the solution you'd like**
Interpret groups in output and make them expandable

**Describe alternatives you've considered**
None

**Additional context**
Documentation on groups: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

Thanks for the awesome plugin!

**Comment by cunla** [comment]
Hi, I just noticed this, sorry for the late response. 
I realized logs performance is not great and there is a limit on the console size.
So I decided to have jobs information (titles, status, url to logs).
I will eventually add the logs per job.

**Comment by cunla** [comment]
I believe the current way of folding steps works best.
