### ISSUE TITLE
Actions for incorrect project displayed when multiple projects are open

### ISSUE THREAD

**Issue by tSchubes** [cunla/ghactions-toolbar#27]
**Describe the bug**
Plugin shows actions for incorrect project when multiple IDE windows are open with different projects in each

**To Reproduce**
1. Open multiple projects which all contain GitHub workflows in separate IDE windows (project A & project B)
2. Open the Github Actions tab in both windows
3. Note that only the actions for project A are displayed in both projects A and B
4. Open another window with project C
5. Note that Actions tab in the windows for project A and B now attempt to display the actions for project C unsuccessfully

**Expected behavior**
The actions tab in each window should include the actions for the project that's open in that window

**Screenshots**
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/13031339/179135289-eed64018-231c-4276-9b18-70cb4b777ba0.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.2
 - JetBrains product + version: WebStorm 2022.1.2

**Comment by cunla** [comment]
Can you provide me with the full text in the error window? I have having a tough time replicating it since it does not allow to run 2 IDEs during development

**Comment by cunla** [comment]
fixed
