### ISSUE TITLE
Names of git remotes in GitHub Actions tabs instead of repository names

### ISSUE THREAD

**Issue by Dasperal** [cunla/ghactions-toolbar#38]
**Is your feature request related to a problem? Please describe.**

I have several git remotes pointing to the forks of the same project. This results in GitHub Actions tabs having identical names because forked repositories usually have identical repository names.
![Снимок](https://user-images.githubusercontent.com/55364443/191844868-79522806-0bf1-461c-8580-08cbf265405d.PNG)

**Describe the solution you'd like**

Option to show names of git remotes (`origin`, `upstream`, etc.) instead of repository names in GitHub Actions tabs. This will be consistent with other git related tool windows.

**Describe alternatives you've considered**

Option to show full repository names, e.g., `Username/Repo`.

**Comment by cunla** [comment]
Which other tools you are referring to - Can you provide links?
I am considering addressing this with the ability to rename tabs.

**Comment by Dasperal** [comment]
> Which other tools you are referring to?

The JetBrains Git plugin, tho, it just represents Git's interface, so I should probably refer to Git itself.
I meant the names of remote branches on Git > Log tab and in Git Branches popup.
